<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PenginapanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('penginapan')->insert([
            // ======== SURABAYA ========
            [
                'name' => 'Rumah Kertajaya',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Akomodasi nyaman dengan kolam renang outdoor dan fasilitas barbekyu.',
                'price' => 500000,
                'rating' => 8.7,
                'image_url' => 'images/rumahkertajaya.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2756,
                'longitude' => 112.6417,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'House of Dharmawan',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Akomodasi dengan taman dan lounge bersama, WiFi gratis.',
                'price' => 600000,
                'rating' => 7.1,
                'image_url' => 'images/surabaya.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2574,
                'longitude' => 112.7521,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kana Citra Guest House',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Berlokasi di Surabaya, 13 km dari Stasiun Kereta Pasar Turi Surabaya, Kana Citra Guesthouse menyediakan akomodasi dengan kolam renang outdoor, parkir pribadi gratis, lounge bersama, dan teras.',
                'price' => 750000,
                'rating' => 8.0,
                'image_url' => 'images/surabaya2.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2514,
                'longitude' => 112.7386,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Home Guesthouse',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Berlokasi di Surabaya, 6,9 km dari Monumen Kapal Selam, HOME Guesthouse menyediakan akomodasi dengan WiFi gratis dan parkir pribadi gratis.',
                'price' => 850000,
                'rating' => 7.8,
                'image_url' => 'images/surabaya3.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2682,
                'longitude' => 112.7427,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Surabaya Homey near Unair Syariah',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Berlokasi di Surabaya, sejauh 4,8 km dari Stasiun Kereta Gubeng dan 5,1 km dari Monumen Kapal Selam, Surabaya Homey near UNAIR Syariah menyediakan akomodasi dengan teras, WiFi gratis di seluruh area.',
                'price' => 900000,
                'rating' => 7.7,
                'image_url' => 'images/surabaya4.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2562,
                'longitude' => 112.7314,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ======== BANDUNG ========
            [
                'name' => 'Laswi Syariah Guesthouse',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Berlokasi sejauh 13 menit jalan kaki dari Trans Studio Bandung dan 2,9 km dari Braga City Walk, Laswi Syariah Guest House menyediakan kamar dengan AC dan kamar mandi pribadi di Bandung. ',
                'price' => 800000,
                'rating' => 8.2,
                'image_url' => 'images/bandung.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9175,
                'longitude' => 107.6191,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'The W Anvenue',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Berlokasi strategis di wilayah Hegarmanah di Bandung, The W Avenue berlokasi 1,7 km dari Cihampelas Walk (Ciwalk), 3,6 km dari Gedung Sate, dan 5 km dari Braga City Walk.',
                'price' => 700000,
                'rating' => 7.9,
                'image_url' => 'images/bandung2.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.8605,
                'longitude' => 107.6154,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'La Grande by Djitu Hospitality',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Berlokasi sejauh 12 menit jalan kaki dari Braga City Walk dan 1,7 km dari Gedung Sate, La Grande by Djitu Hospitality menyediakan kamar dengan AC dan kamar mandi pribadi di Bandung',
                'price' => 600000,
                'rating' => 8.0,
                'image_url' => 'images/bandung3.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9147,
                'longitude' => 107.6098,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rumah Eyang Homestay',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Berlokasi di Bandung, 18 km dari Trans Studio Bandung, 19 km dari Gedung Sate, dan 20 km dari Braga City Walk, Rumah Eyang Homestay menyediakan akomodasi dengan balkon dan WiFi gratis.',
                'price' => 400000,
                'rating' => 7.5,
                'image_url' => 'images/bandung4.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9034,
                'longitude' => 107.6082,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Uma Gati',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Uma Gati menyediakan pemandangan gunung dan WiFi gratis di Bandung, 6,4 km dari Gedung Sate dan 6,7 km dari Cihampelas Walk (Ciwalk).',
                'price' => 900000,
                'rating' => 9.0,
                'image_url' => 'images/bandung5.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.8542,
                'longitude' => 107.6046,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ======== SEMARANG ========
            [
                'name' => 'Spot on 90780 Gang Tengah Homestay Syariah',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Guest house sederhana dengan fasilitas yang lengkap.',
                'price' => 300000,
                'rating' => 6.9,
                'image_url' => 'images/semarang.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.0052,
                'longitude' => 110.4381,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sky Guesthouse',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Hotel bergaya kolonial di tengah kota dengan akses mudah ke tempat wisata.',
                'price' => 650000,
                'rating' => 8.4,
                'image_url' => 'images/semarang2.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9875,
                'longitude' => 110.4216,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Amarilis Guesthouse Semarang',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Hotel modern yang terletak dekat dengan Simpang Lima.',
                'price' => 700000,
                'rating' => 8.0,
                'image_url' => 'images/semarang3.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9932,
                'longitude' => 110.4267,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Guesthouse Bintang Tiga',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Villa tenang dengan pemandangan perbukitan di Ambarawa.',
                'price' => 850000,
                'rating' => 9.1,
                'image_url' => 'images/semarang4.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2631,
                'longitude' => 110.4035,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Omah Pelem Guesthouse Semarang',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Hotel butik bergaya vintage di kawasan Kota Lama Semarang.',
                'price' => 750000,
                'rating' => 8.8,
                'image_url' => 'images/semarang5.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9733,
                'longitude' => 110.4287,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
