<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PenginapanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('penginapan')->insert([
            // ======== SURABAYA ========
            [
                'name' => 'Rumah Kertajaya',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Akomodasi nyaman dengan kolam renang outdoor dan fasilitas barbekyu.',
                'price' => 500000,
                'rating' => 8.7,
                'image_url' => 'images/rumahkertajaya.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2756,
                'longitude' => 112.6417,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'House of Dharmawan',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Akomodasi dengan taman dan lounge bersama, WiFi gratis.',
                'price' => 600000,
                'rating' => 7.1,
                'image_url' => 'images/surabaya.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2574,
                'longitude' => 112.7521,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hotel Tunjungan',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Hotel dengan akses langsung ke pusat perbelanjaan Tunjungan Plaza.',
                'price' => 750000,
                'rating' => 8.3,
                'image_url' => 'images/hotel_tunjungan.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2514,
                'longitude' => 112.7386,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Grand Surabaya Hotel',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Hotel mewah di pusat kota dengan fasilitas kolam renang indoor.',
                'price' => 850000,
                'rating' => 8.9,
                'image_url' => 'images/grand_surabaya.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2682,
                'longitude' => 112.7427,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Surabaya Heritage Hotel',
                'location' => 'Surabaya, Jawa Timur',
                'description' => 'Hotel bergaya klasik dengan pemandangan kota yang indah.',
                'price' => 900000,
                'rating' => 9.0,
                'image_url' => 'images/surabaya_heritage.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.2562,
                'longitude' => 112.7314,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ======== BANDUNG ========
            [
                'name' => 'Villa Bandung Asri',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Villa nyaman dengan pemandangan pegunungan yang indah.',
                'price' => 800000,
                'rating' => 8.2,
                'image_url' => 'images/villa_bandung_asri.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9175,
                'longitude' => 107.6191,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dago Hill Hotel',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Hotel di kawasan Dago dengan udara sejuk dan pemandangan alam.',
                'price' => 700000,
                'rating' => 7.9,
                'image_url' => 'images/dago_hill.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.8605,
                'longitude' => 107.6154,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bandung City Hotel',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Hotel modern di pusat kota Bandung dekat pusat perbelanjaan.',
                'price' => 600000,
                'rating' => 8.0,
                'image_url' => 'images/bandung_city_hotel.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9147,
                'longitude' => 107.6098,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cihampelas Guest House',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Guest house nyaman dengan akses ke area belanja Cihampelas.',
                'price' => 400000,
                'rating' => 7.5,
                'image_url' => 'images/cihampelas_guesthouse.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.9034,
                'longitude' => 107.6082,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Setiabudi Villa',
                'location' => 'Bandung, Jawa Barat',
                'description' => 'Villa mewah dengan taman indah di kawasan Setiabudi.',
                'price' => 900000,
                'rating' => 9.1,
                'image_url' => 'images/setiabudi_villa.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -6.8542,
                'longitude' => 107.6046,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ======== SEMARANG ========
            [
                'name' => 'Guest House Semarang',
                'location' => 'Semarang, Jawa Tengah',
                'description' => 'Guest house sederhana dengan fasilitas yang lengkap.',
                'price' => 300000,
                'rating' => 6.9,
                'image_url' => 'images/guest_house_semarang.webp',
                'available_from' => Carbon::now(),
                'available_to' => Carbon::parse('2024-12-31'),
                'latitude' => -7.0052,
                'longitude' => 110.4381,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Tambahkan 4 data lagi untuk Semarang...
        ]);
    }
}
